### PR TITLE
Adding penelope EM model to the physics list

### PR DESCRIPTION
**Pull request by LiangLiu212**
Adding penelope EM model to the physics list

### CODE REVIEW

**Comment by knoepfel** [comment]
@LiangLiu212 and @hgreenlee, is this a PR for MicroBooNE's production needs?

**Comment by knoepfel** [comment]
@LiangLiu212 and @hgreenlee, is this a PR for MicroBooNE's production needs?

**Comment by LiangLiu212** [comment]
> @LiangLiu212 and @hgreenlee, is this a PR for MicroBooNE's production needs?

Yes, we want to revisit the systematic effect of the Geant4 electromagnetic model in MicroBooNE. Currently, larsim package already have the standard EM and livermore EM model. So I put penelope EM model in there and people can change the EM model by 

`services.LArG4Parameters.EnabledPhysics:    [ "penelopeEm",
                                              "FastOptical",
                                              "SynchrotronAndGN",
                                              "Ion",
                                              "Hadron",
                                              "Decay",
                                              "HadronElastic",
                                              "Stopping"]`

I work with @hgreenlee  now. We think these em models are potentially of interest beyond MicroBooNE. I think it could be good if these larsim updates available in the integration release. If so, I'd like to open a pull request to the develop branch.

best regards!
Liang

**Comment by lgarren** [comment]
Thanks @LiangLiu212 

@hgreenlee has the permissions and instructions for merging this PR with the MicroBooNE production branch.  We will leave the resolution of this PR to MicroBooNE.  @hgreenlee, please let us know if there is a problem.

We look forward to a new PR for the develop branch.

**Pull request merged**
