### PR TITLE
Fix in CORSIKAGen documentation format

### PR DESCRIPTION
**Pull request by PetrilloAtWork**

### CODE REVIEW

**Comment by PetrilloAtWork** [comment]
Command used to submit the request: `hub pull-request -m "Fix in CORSIKAGen documentation format"`.
Not sure why it shows "No description provided", since that stuff in `-m` looks like a description to me (I chose it to be the same as the commit message).

**Comment by gartung** [comment]
First line becomes the title. Subsequent lines are the body of the descriprion. You can use the --edit flag to bring up the editor.

**Comment by knoepfel** [comment]
approve

**Comment by knoepfel** [comment]
trigger build

**Pull request merged**
