### PR TITLE
Proposal for implementation of issue #22628 (improvements in sim::OnePhoton)

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Proposal for implementation of [issue #22628](https://cdcvs.fnal.gov/redmine/issues/22628) (improvements in `sim::OnePhoton`).
This copes with the ripples from the change in the data product.

I admit I slipped in an optimisation to `LegacyLArG4` to avoid the introduction of a ephemeral large buffer when saving energy depositions.

### CODE REVIEW

**Review by knoepfel — COMMENTED** [review]
Approve

**Comment by knoepfel** [comment]
Approve

**Comment by lgarren** [comment]
@PetrilloAtWork  Would you please update the ublite feature branch to match the head of develop?  The uboone CI is failing due to version mismatch.  Thanks.
https://dbweb5.fnal.gov:8443/LarCI/app/ns:uBooNE/view_builds/index?offset=0&builds=uboone_ci/4943&builds=

**Comment by lgarren** [comment]
@PetrilloAtWork  There are problems with the c7 build.  CI logs here:
https://dbweb5.fnal.gov:8443/LarCI/app/view_builds/index?offset=0&builds=lar_ci/8601&builds=

**Comment by lgarren** [comment]
The c7 build problems have been fixed and the c7 CI tests are OK.
https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/8607&builds=

Note that the c7 ICARUS CI build is broken at this time for other reasons.

**Pull request merged**
