### PR TITLE
Add module and tool for photon fast simulation

### PR DESCRIPTION
**Pull request by Healthborn**
Add module and tool for photon fast simulation

### CODE REVIEW

**Comment by lgarren** [comment]
@Healthborn LArSoft use of tensorflow is modularized.  That means it is only meant to be used through larrecodnn.

**Comment by Healthborn** [comment]
> 

@lgarren, I know there is a product larsimdnn, can I commit to that product? But it seems larsimdnn is out of date.

**Comment by knoepfel** [comment]
@Healthborn, thanks for the feedback and the PR.  The SciSoft team will discuss this and propose a way forward.

**Comment by knoepfel** [comment]
@Healthborn, we think this PR belongs in https://github.com/LArSoft/larsimdnn.  However, we need to update that repository to support cetmodules and we will supply the `FindTensorFlow.cmake` module in a different way.  Once we have those things in place, we will ask you to close this PR and create a new PR in `larsimdnn`.

**Comment by Healthborn** [comment]
Thank you @knoepfel!

**Comment by lgarren** [comment]
@Healthborn We believe that the head of develop of larsimdnn is now ready for you to use.  You will need to build both larfinder (new) and larsimdnn.   Please contact the SciSoft team if you have any problems.

**Comment by Healthborn** [comment]
@lgarren I'm sorry, I don't understand what do you mean by "You will need to build both larfinder (new) and larsimdnn". Can I check in my code to only larsimdnn?

**Comment by lgarren** [comment]
@Healthborn  You should only commit your code to larsimdnn.  However, the tensorflow find module is now in the new larfinder package.  This allows the same find module to be used by both larsimdnn and larrecodnn.  Since larfinder is not yet part of a release, you will need to build both larsimdnn and larfinder.

**Comment by Healthborn** [comment]
@lgarren  Does that mean: I need not add \Modules\FindTensorFlow.cmake to my checkin, and I need only check in my code and update the CMakeLists.txt?

**Comment by Healthborn** [comment]
@lgarren When I tried to check out larfinder, I got the following error:
mrb g larfinder
INFO: Unable to verify write access for larfinder, falling back to read-only.
ERROR: Unable to verify read access to remote http://cdcvs.fnal.gov/projects/larfinder.

**Comment by lgarren** [comment]
@Healthborn, I suggest sending further quesxtions to scisoft-team@fnal.gov.  You'll need a newer mrb, which is not yet available on larsoft cvmfs.   You can just `git clone git@github.com:LArSoft/larfinder.git` and then `mrb uc`

**Comment by Healthborn** [comment]
@lgarren I tried to run: git clone git@github.com:LArSoft/larfinder.git, and got the following error:
Cloning into 'larfinder'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by lgarren** [comment]
Oh, right.  You need the read-only clone: `https://github.com/LArSoft/larfinder.git`

**Comment by Healthborn** [comment]
It works! Many thanks!

**Pull request closed without merging**
