### PR TITLE
Refactoring of PhotonPropagation classes to substantially reduce overhead

### PR DESCRIPTION
**Pull request by ikatza**
While inspecting the code for bugs I tend to make changes to the code to make tests. I've collected enough of these changes that it makes sense to put them together neatly.

This PR improves performance times and hopefully improves the organisation of the code. The processing time per event doesn't change much, but the initialisation is substantially reduced.

Functionality stays largely the same, but there is is a small change in the time propagation distribution, which is expected. 

Main changes:

- Change from using ROOT RNG to CLHEP::RandGeneral
- Create PhotonPropagationUtils to host functions defined twice elsewhere
- Use references of the fcl parameters, instead of copying the objects
- Move PropagationTimeModel and SemiAnalyticalModel to the `phot` namespace
- Simplify the initialisation and reduce the number of class members, moving several things around and creating some functions to use them during initialisation
- Round scintillation times instead of flooring them
- Stop using TVector3
- Regularise the syntax and clean comments

I'm opening this PR as a draft to accept possible suggestions to improve the code. I've created a CI test, but it hasn't been enabled yet. I'll update this PR with the results from the test once I have them.

### CODE REVIEW

**Comment by ikatza** [comment]
Since I updated the namespace, the SBNSoftware needs these two PRs to be able to compile:

https://github.com/SBNSoftware/sbndcode/pull/321
https://github.com/SBNSoftware/sbncode/pull/338

**Comment by lgarren** [comment]
trigger build with pull requests #111, SBNSoftware/sbncode#338, SBNSoftware/sbndcode#321

**Comment by lgarren** [comment]
@ikatza It seems that the DUNE code will need a PR: https://dbweb8.fnal.gov:8443/LarCI/app/ns:dune/storage/docs/2023/03/07/buildDUNE%23MzwCEAy.log

**Comment by ikatza** [comment]
I've made the PR in `duneopdet` now @lgarren

**Comment by lgarren** [comment]
Thanks @ikatza

**Comment by lgarren** [comment]
The DUNE CI tests are now completed with warnings: 
https://dbweb8.fnal.gov:8443/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/15018&builds=

**Comment by lgarren** [comment]
approve

**Pull request merged**
