### PR TITLE
Added SimEnergyDeposits support in MergeSimSources

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
The module `MergeSimSources` is used to merge together the simulation results of multiple `LArG4` (legacy) module sessions. One common use is to simulate only part of an event through GEANT4, evaluate some requirements and if the event passes them, proceed simulating the rest of the event and eventually merging all together. Given the random nature of GEANT4 simulation, it is necessary for the first, partial simulation to be preserved, since simulating it anew might result in the requirements not being satisfied any more (for example, a particle close to the border of the TPC might cross it in the partial simulation, but then miss it in the second one).

`MergeSimSources` can manage almost all `LArG4` data products, with the noticeable exception of `sim::SimEnergyDeposit`. This commit fills that gap.

The pull request also includes two commits aimed to "refresh" the coding style of the module to reflect more modern practices enabled by newer _art_ and LArSoft versions.

The original author of the module is @wesketchum.

The code is based on `v09_14_00` and it has been compiled and tested with `icaruscode` (`e19:prof`).
The testing included the verification of the presence of the expected data products, and of their expected size.

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by knoepfel** [comment]
Looks good, @PetrilloAtWork.  Will approve after L2 approval has been granted.

**Comment by lgarren** [comment]
@PetrilloAtWork  The c7 build has failed.  See https://dbweb8.fnal.gov:8443/LarCI/app/storage/docs/2021/02/10/buildLArSoft%23TboFJLW.log

**Comment by PetrilloAtWork** [comment]
Groan. Thank you, Lynn. I have fixed the code via GitHub... I hope it will go well.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The CI tests are normal now.  Thanks @PetrilloAtWork

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
