### PR TITLE
[FEAT] Add photon fast simulation module based on GAN graph

### PR DESCRIPTION
**Pull request by Healthborn**
1. Introduce  a new photon fast simulation module based on the graph produced from GAN network.
2. In order to load the graph in larsfot, a tool has been introduced: TFLoader.
3. This tool need the tensorflow header file.
4. To compile the module/tool, the top level CMakeLists.txt should be also be updated.
5. I have tested the compiling, but I prefer the expert to update the top level CMakeLists.

### CODE REVIEW

**Comment by knoepfel** [comment]
@Healthborn, could you present this proposal at the next LArSoft coordination meeting on Dec. 1.  There are many complications with TensorFlow, and we'd like to hear exactly what you require.

**Comment by Healthborn** [comment]
No problem, I will present at the LArSoft Coordination meeting. on Dec. 1

**Comment by lgarren** [comment]
@Healthborn  A skeleton of larsimdnn now exists on github.  You will need mrb v4_04_01 (now on larsoft cvmfs).  In order to make a complete example, I created a larsimdnn/PhotonPropagation directory.  Please rename that directory to something more appropriate for this work.  Let us know if you have any problems.

**Comment by knoepfel** [comment]
@Healthborn, will you have the chance to look at the `larsimdnn` skeleton soon?

**Comment by Healthborn** [comment]
@knoepfel, sure I will do it within this week.

**Comment by Healthborn** [comment]
@knoepfel, the `larsimdnn` skeleton looks nice. Thanks for the great work.
The compiling also works after I add a test CMakeList.txt file to the folder `/larsimdnn/PhotonPropagation`.
I will continue testing it and try to migrate all the machine learning code to this repository.

**Comment by lgarren** [comment]
Thanks @Healthborn   Please also consider renaming the PhotonPropagation directory to avoid confusion with larsim.

**Comment by knoepfel** [comment]
@Healthborn, what is the status of the larsimdnn PR?

**Comment by Healthborn** [comment]
I go ahead to close this PR and check in the code into larsimdnn on this Thursday.

**Pull request closed without merging**
