### PR TITLE
Module to convert PhotonHits into SimPhotons/SimPhotonsLite.

### PR DESCRIPTION
**Pull request by asanchezcastillo**
New module to convert PhotonHits from artg4tk into SimPhotons/SimPhotonsLite. Output is fhicl-configurable.

### CODE REVIEW

**Comment by lgarren** [comment]
@asanchezcastillo the new CMakeLists.txt file can be greatly simplified.  Also note that in this case the libraries should be explicitly listed as PRIVATE.
```
cet_build_plugin(PhotonHitConverter art::module
      SOURCE PhotonHitConverter_module.cc
      LIBRARIES PRIVATE
        larcorealg::Geometry
        larcore::Geometry_Geometry_service
        lardataobj::Simulation
        artg4tk::pluginDetectors_gdml
)

install_source()
```

It appears that this code can be added to larg4 instead of larsim.  Are you able to make a new PR for that?

**Comment by lgarren** [comment]
@asanchezcastillo Also, please make a feature branch for your PR instead of using "develop".

**Comment by asanchezcastillo** [comment]
Yes, I will do the PR for that. Should I add the source file under larg4/larg4/Analysis/ ?

**Comment by lgarren** [comment]
> Yes, I will do the PR for that. Should I add the source file under larg4/larg4/Analysis/ ?

Thanks @asanchezcastillo   
@hanswenzel, do you agree with the proposal to add this new module to larg4/larg4/Analysis/ ?

**Comment by lgarren** [comment]
@asanchezcastillo  After a closer look, this PR belongs in larsim.  Please update the CMakeLists.txt as mentioned here: https://github.com/LArSoft/larsim/pull/113#issuecomment-1496628421 so we can move forward.

**Comment by asanchezcastillo** [comment]
I have updated the CMakeList.txt file and created a new PR (https://github.com/LArSoft/larsim/pull/116) with a new feature branch. Should I close this PR at this point?

**Comment by hanswenzel** [comment]
I think that's fine with me.

Hans


--

Dr. Hans Wenzel



Physics and Detector Simulation

Fermi National Accelerator Laboratory

P.O. Box 500, MS 223

Batavia, Illinois 60510

USA



630 840 6034 office

331 250 9342  mobile

home.fnal.gov/~wenzel<http://home.fnal.gov/~wenzel>

***@***.******@***.***>

________________________________

**Comment by lgarren** [comment]
Thanks for the new PR

**Pull request closed without merging**
