### PR TITLE
Adding penelope EM model to the physics list

### PR DESCRIPTION
**Pull request by LiangLiu212**
Adding penelope EM model to the physics list

We revisit the systematic effect of geant4 EM model in MicroBooNE. We want to compare the differences among the standard, Livermore and Penelope EM models. The larsim has standard and Livermore EM model in the default option. I add the Penelope model. 

I find larsim package changes a lot from MCC9 to MCC10. This PR passes the compiling. But I haven't run it yet.

Best regards!

Liang Liu

### CODE REVIEW

**Comment by lgarren** [comment]
code-checks

**Comment by greenc-FNAL** [comment]
@hanswenzel Would you be able to review this with respect to merging into the current LArSoft develop?

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
@LArSoft/level-2-managers Please review and approve or comment.

**Comment by tomjunk** [comment]
The commit looks harmless enough -- looks optional and if one isn't using Penelope, it looks like it won't break existing workflows.  But Hans is the designated reviewer, and I do have a question.  Is this PR dependent on PR139, which looks like it has more nontrivial Penelope-related additions?

https://github.com/LArSoft/larsim/pull/139

The titles of these two PRs are the same.

That said, I think DUNE's low-energy team it interested in testing it.  I've contacted Dan Pershey on this after Erica brought it up at a LArSoft coordination meeting.

**Comment by lgarren** [comment]
@tomjunk  The other PR is for a MicroBooNE branch.  Hans says this PR has no problems, since it simply adds an option to the physics list.  The physics list is only relevant in larg4legacy.

**Comment by lgarren** [comment]
approve

**Pull request merged**
