### PR TITLE
Feature/rhatcher g4alt

### PR DESCRIPTION
**Pull request by nusense**
this is a coupled pull request with a corresponding nug4 pull request that removes the old self-supported physics list factory in favor of the official G4 g4alt factory.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build with pull requests #75, LArSoft/larg4#29

**Comment by lgarren** [comment]
CI tests appear to be normal.  uboone unit tests were run locally and are fine.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
