### PR TITLE
Refactor EventWeight interface to GENIE v3

### PR DESCRIPTION
**Pull request by sjgardiner**
To be discussed at 23 Feb 2021 LArSoft Coordination Meeting (https://indico.fnal.gov/event/47983/)

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The CI tests are normal, but it is our understanding that the CI will not test required changes.

**Comment by yangtj207** [comment]
Steven and I tested this PR on ArgoNeuT simulation and it works. Can we approve and merge this? Thanks.

**Comment by lgarren** [comment]
@yangtj207  We are waiting for documentation from @sjgardiner  We agreed a while back that that was the next step.

**Comment by lgarren** [comment]
@sjgardiner  Do you have documentation for the required changes yet???

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@sjgardiner  The c7 build failed with an unused variable warning.  The ICARUS CI failed, but the failure may be unrelated to this change.   Please, however, take a look at the uboone failures.   It appears that the DUNE CI did not run.  We will investigate that.

**Comment by lgarren** [comment]
Here is the dune CI test: https://dbweb0.fnal.gov/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/11056&builds=

**Comment by sjgardiner** [comment]
Thanks, Lynn! The uboone failures aren't related in any obvious way to the changes on the feature branch. One of them issued the message "HTTP error from https://dbdata0vm.fnal.gov." @hgreenlee, can you please provide guidance on these?

**Comment by hgreenlee** [comment]
Hello,

Wednesday was a database downtime for conditions database (and other database) migration to new hardware.  After the migration, the conditions database server was broken until Thursday afternoon.

Herb

**Comment by sjgardiner** [comment]
Okay, thanks @hgreenlee, that's good to know. @lgarren, I just pushed a new commit that should resolve the c7 build failure. Hopefully things work out better now that the databases are (I think) back up.

**Comment by yangtj207** [comment]
trigger build

**Comment by lgarren** [comment]
The CI tests are now normal.  

The next step is to get signoff from the experiments for this change.

**Comment by yangtj207** [comment]
ArgoNeuT is OK with this PR.

**Comment by yangtj207** [comment]
Hi @lgarren, Would you email the experiment liaisons to sign off on this PR? I am sure all experiments will benefit from this. Thanks.

**Comment by lgarren** [comment]
@yangtj207  Erica has sent the email and we mentioned this in the coordination meeting.  It will be included next week as long as there are no objections from the experiments.

**Comment by yangtj207** [comment]
+1

**Comment by lgarren** [comment]
approve

**Pull request merged**
