### PR TITLE
added new toy larg4 detector based on refactored larg4 and updated SimWire_module with new noise models and response functions

### PR DESCRIPTION
**Pull request by mhlswang**

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by knoepfel** [comment]
I don't see any major issues.  L1 approval should be granted when ready.

**Comment by lgarren** [comment]
@mhlswang The c7 build has failed with an unused variable.  See https://dbweb8.fnal.gov:8443/LarCI/app/storage/docs/2021/02/10/buildLArSoft.log

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The CI tests are normal.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
