### PR TITLE
Accept multiple instances of SimEnergyDeposit as input

### PR DESCRIPTION
**Pull request by wenqiang-gu**
The motivation of this pull request is to support the cryostat-side TPC simulation for protoDUNE-SP. As larg4 produced two instances of SimEnergyDeposit (`LArG4DetectorServicevolTPCActive` and `LArG4DetectorServicevolTPCActiveOuter`), it is suggested to merge them in the recombination simulation and feed them to the WireCell TPC simulation. 

Below is an example of the W-view waveforms given two energy depos from the cryostat (x=-3750mm) and the TPC side (x=-3550mm), respectively.
image

### CODE REVIEW

**Comment by wenqiang-gu** [comment]
To use this feature in the protoDUNE-SP simulation, one also needs some updates in the dunetpc package: https://cdcvs.fnal.gov/redmine/projects/dunetpc/repository/revisions/b441ae618601fc4a54082503d3765c000b584241

**Comment by yangtj207** [comment]
trigger build

**Comment by lgarren** [comment]
Are the changes needed by dune in a feature branch, or were they pushed to the head of develop?   Will other experiments need similar changes?

**Comment by wenqiang-gu** [comment]
> Are the changes needed by dune in a feature branch, or were they pushed to the head of develop? Will other experiments need similar changes?

The corresponding update for `dunetpc` has been pushed to the develop branch. 

As far as I know, so far DUNE/protoDUNE is the only user for this module (larsim/IonizationScintillation).

**Comment by lgarren** [comment]
All unit tests are fine with this PR.

**Comment by lgarren** [comment]
approve

**Pull request merged**
