### PR TITLE
Add scintillation prescaling factor to Correlated alg

### PR DESCRIPTION
**Pull request by wforeman**

### CODE REVIEW

**Comment by aihimmel** [comment]
Diffs all look fine to me. Unless the CI tests turn up something unexpected I think this is ready to go. (Thanks for adding this in, Will.)

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@aihimmel Would you formally approve this by typing "approve" as a single comment?  Thanks

**Comment by aihimmel** [comment]
Yes, I just didn't want to jump ahead of the CI tests in case there were any surprises.

**Comment by aihimmel** [comment]
Approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
