### PR TITLE
Flexible path for radiogen files

### PR DESCRIPTION
**Pull request by lpaulucc**
Radiological files needed for the next FD dune production are in StashCache but the RadioGen module looked for files with a hard coded path. A new fhicl parameter was added to the module so that it is flexible enough to find files with a change in the configuration block and not the module itself.

### CODE REVIEW

**Comment by knoepfel** [comment]
@lpaulucc, this looks like a good improvement.  Now that the file-path is configurable, at the very least, you should add a check to make sure that the last character is a forward slash `'/'`.

**Comment by lpaulucc** [comment]
Thank you @knoepfel. I have added the check of the last character on the path and included an exception if it is not a forward slash. Please let me know if I didn't use the appropriate case for that.

**Comment by knoepfel** [comment]
trigger build

**Comment by knoepfel** [comment]
@lpaulucc, the `'/'` check looks good.  We'll see how the CI reacts to the change.

**Comment by lgarren** [comment]
@LArSoft/level-2-managers please review and approve or comment

**Comment by tomjunk** [comment]
Approved

Looks fine.  Thanks!

**Comment by lgarren** [comment]
approve

**Pull request merged**
