### PR TITLE
Store original track id for sim energy deposits

### PR DESCRIPTION
**Pull request by bear-is-asleep**

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
@LArSoft/level-2-managers please approve or comment!

**Comment by tomjunk** [comment]
Approved.

This fills in a value for an argument in the constructor which defaults to zero which presumably is worse than an actual value for the original track ID.  I only looked at the commits and the DUNE tests which are fine.

**Comment by lgarren** [comment]
approve

**Pull request merged**
