### PR TITLE
Replace coord subtraction with pitch to prevent negative distances

### PR DESCRIPTION
**Pull request by JamesJieranShen**
Part of redmine Issue https://cdcvs.fnal.gov/redmine/issues/26277#change-85576.

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
approve

**Comment by knoepfel** [comment]
Thanks, @JamesJieranShen, for the PR.  Does this change break any already-working jobs?

**Comment by absolution1** [comment]
Hi @knoepfel I don't think it does, but other L2s are welcome to comment.  We know it fixes the radiological issue we were seeing in the DUNE FD.  It also looks like it does not break anything in SBND (according to the CI results) where the refactored LArG4 is already used.

**Comment by knoepfel** [comment]
approve

Let's go ahead then, Dom.  Thanks very much.

**Comment by lgarren** [comment]
trigger build

testing with the art 3.09 release

**Comment by knoepfel** [comment]
trigger build

**Pull request merged**
