### PR TITLE
Semi-analytical light simulation xenon updates

### PR DESCRIPTION
**Pull request by pgreen135**
This PR adds configuration for xenon wavelength light absorption length to the semi-analytical light simulation model that is required by DUNE-VD. It also fixes two minor bugs / issues that were identified during the testing of this. 

These changes shouldn't impact any other experiments. To enable them in DUNE-VD the following PRs are also required:

https://github.com/DUNE/duneopdet/pull/26
https://github.com/LArSoft/lardataalg/pull/39

### CODE REVIEW

**Comment by pgreen135** [comment]
Looking at the CI outputs the warnings / failures do not seem to be related to this particular PR

**Comment by lgarren** [comment]
> Looking at the CI outputs the warnings / failures do not seem to be related to this particular PR

@pgreen135 agreed   
Now if we can just get @LArSoft/level-2-managers approval...

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
